theme: "modern"

# Optional overrides for avatar and favicon
# If not set, avatar defaults to resume.basics.image
favicon: "img/favicon.svg"
avatar: "img/favicon.svg"

# Visual overrides that themes can use
style:
  primaryColor: "#3b3763"
  secondaryColor: "#1f1e32"
  accentColor: "#399ba8"

  # Scaling Factors (1.0 = Default)
  fontSizeScale: 0.9 # Scales the base 10pt font
  spacingScale: 0.9 # Global density scaler
  pagePaddingScale: 1.0 # Specific multiplier for page margins
  sectionGapScale: 1.0 # Specific multiplier for section separation
  sidebarRatio: 0.3 # Width ratio of the sidebar (e.g. 0.3 for 30%)

# Toggles
features:
  showPhoto: false
  showIcons: true
  showSkillBars: true
  showLocation: true
  showReferences: false # If false, shows "References available upon request"

